### ISSUE TITLE
unclosed if statement

### ISSUE THREAD

**Issue by sergey-tikhonenko** [ivanesmantovich/xkbswitch.nvim#5]
looks like you have an extra space in the `else if` statement in the latest fix ( # 4 )
see https://github.com/ivanesmantovich/xkbswitch.nvim/blob/b3cd50c66adfa3dcaf04f7a87dd6bbeefe573e10/lua/xkbswitch.lua#L48
error log:
```
....local/share/nvim/lazy/lazy.nvim/lua/lazy/core/cache.lua:172: .../.local/share/nvim/lazy/xkbswitch.nvim/lua/xkbswitch.lua:123: 'end' expected (to close 'for' at line 45) near '<eof>'

# stacktrace:
  - ~/.config/nvim/lua/config/lazy.lua:9
  - ~/.config/nvim/init.lua:2
```

**Comment by ivanesmantovich** [comment]
Whoops... Thanks a lot!
