### ISSUE TITLE
"/" search with auto layout switching

### ISSUE THREAD

**Issue by wh00d** [ivanesmantovich/xkbswitch.nvim#8]
Hello!

You can use `CmdlineLeave` and `CmdlineEnter` autocmds if it's possible.

Thank you for your great plugin!

**Comment by ivanesmantovich** [comment]
Thank you for your kind words.
At first I implemented your request, but now I've reverted my changes.

The most common use of Cmdline by far is `:w` and `:q`
If your last action was to write a comment in a non-English language, then when you try to cowboy-style quickly save it as you've done a million times before, you realize that your layout is not English and you've got an error.

So I think that what you asking for will bring more harm than good. Sorry!

**Comment by ashk3t** [comment]
Thank you for your response!

Sorry for bad feature request description. So I want to clarify: auto switching back US layout on leaving cmdline, without saving persistent layout state. I don't like switching layout manually twice when I jump between words in native language markdown notes. It makes me sad:(

**Comment by ivanesmantovich** [comment]
Implemented!
I don't see how this can be an inconvenience, I hope I'm not missing anything...
