### ISSUE TITLE
Remember used language per buffer

### ISSUE THREAD

**Issue by Andrew15-5** [ivanesmantovich/xkbswitch.nvim#9]
I tried out this plugin, and it only works for 1 instance of Neovim. Furthermore, the language persists between buffers. If multiple buffers/instances will be supported, then this plugin will deserve an ultimate status.

**Comment by ivanesmantovich** [comment]
Thank you for your kind words, but unfortunately I don't think it's possible to laconically save a layout for each buffer / instance, and I think you have a pretty rare use case...
My main goal for this plugin is to keep it as minimal as possible, sorry

**Comment by Andrew15-5** [comment]
Sure. BTW, I tried using some simple keymaps in insert mode: for moving left/right, selecting item from autocompletion drop-down list, deleting a line, but they didn't work. I had to switch to `us` layout. Since there is only `<c-k>` keymap and no `<c-л>` keymap I couldn't use them (keymaps). So it's the only flaw in the plugin so far.

**Comment by Andrew15-5** [comment]
And you should've closed as "won't fix" and not as "completed". You probably still can change that.
